name: Create Production Builds

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production

  submit-android:
    name: Submit to Google Play
    type: submit
    needs: [build-android]
    params:
      build_id: ${{ jobs.build-android.outputs.build_id }}
