name: Create Production Builds

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    type: build
    platform: android
    profile: production

  submit-android:
    name: Submit to Google Play
    type: submit
    platform: android
    needs: build-android
    profile: production
